name: CI/CD Workflow

on:
  push:
    branches:
      - flower

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: pom.xml

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'  # Specify the desired Java distribution
        java-version: '17'  # Specify the desired Java version
        cache: 'gradle'  # Optional: Use caching for Gradle, if applicable

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests
      run: mvn test
