name: CI/CD Workflow

on:
  push:
    branches:
      - flower  # Specify the "flowers" branch here

  pull_request:
    branches:
      - flower  # Specify the "flowers" branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
